name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # نصب SDK و قبول لایسنس‌ها
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # ساختن local.properties تا Gradle بداند SDK کجاست
      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK (verbose)
        run: ./gradlew --version && ./gradlew assembleDebug --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GraceVPN-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
